### ISSUE TITLE
JS2 Week 2 Feedback

### ISSUE THREAD

**Issue by orhantoy** [Nazaqat/hyf-homework#1]
@Nazaqat :v:

## Warmup array exercises / Doubling of number

Nice work here 👍 

## Warmup array exercises / Working with movies

- Exercise 1, 2, 3: ✅ Nice work 💪 A few notes and suggestions:
  - Calling the argument `movie` instead of `items` would be more descriptive.
  - No need to check type of `items.title`.
  - You could simplify these functions to one-liners like: `const shortTitle = movies.filter(movie => movie.title.length <= 5)`
- Exercise 4: You almost have the right solution here. First, `returnTag` should have been an array of movies but it is instead and array of arrays of movies. If you check the output with `console.log` you'll see what I mean. Second, by setting `obj.Tag` you actually modify the movie objects from `movies`, which is not a huge problem but ideally you shouldn't modify that data.
- Exercise 5: ✅ Nice work. A suggestion: try to be consistent with where you have spaces:
  - `movies.filter (items => items.rating > 6).map( items => items.rating)` (your code)
  - `movies.filter(items => items.rating > 6).map(items => items.rating)` (your code with consistent spaces)
- Exercise 6: ✅ Nice! The line gets a bit too long so I would suggest trying to break it into more lines so the code is easier to read.
- Exercise 7: Your solution is close to being correct. You're returning an array of titles but that should have been an array of movies.

## hyfBay - get the okay'est products here - continued

Seems like you got stuck with this one? I'll be happy to help, so feel free to ask questions about this exercise or the other ones.

**Comment by Nazaqat** [comment]
Hi Orhan, Thank you so much for ur valuable feedback & I ll get u back in case of questions 😉🙏
Vh. Nazaqat 


Sendt fra Yahoo Mail til iPhone


Den torsdag, oktober 31, 2019, 1:28 PM skrev Orhan Toy <notifications@github.com>:


@Nazaqat ✌️
 
Warmup array exercises / Doubling of number

Nice work here 👍
 
Warmup array exercises / Working with movies
   
   - Exercise 1, 2, 3: ✅ Nice work 💪 A few notes and suggestions:      
      - Calling the argument movie instead of items would be more descriptive.
      - No need to check type of items.title.
      - You could simplify these functions to one-liners like: const shortTitle = movies.filter(movie => movie.title.length <= 5)

   - Exercise 4: You almost have the right solution here. First, returnTag should have been an array of movies but it is instead and array of arrays of movies. If you check the output with console.log you'll see what I mean. Second, by setting obj.Tag you actually modify the movie objects from movies, which is not a huge problem but ideally you shouldn't modify that data.
   - Exercise 5: ✅ Nice work. A suggestion: try to be consistent with where you have spaces:      
      - movies.filter (items => items.rating > 6).map( items => items.rating) (your code)
      - movies.filter(items => items.rating > 6).map(items => items.rating) (your code with consistent spaces)

   - Exercise 6: ✅ Nice! The line gets a bit too long so I would suggest trying to break it into more lines so the code is easier to read.
   - Exercise 7: Your solution is close to being correct. You're returning an array of titles but that should have been an array of movies.

hyfBay - get the okay'est products here - continued

Seems like you got stuck with this one? I'll be happy to help, so feel free to ask questions about this exercise or the other ones.
